### ISSUE TITLE
Hello，dose editions-39（AI） support Python？

### ISSUE THREAD

**Issue by chenchengyuan** [cloudgrey-io/appiumpro#15]
Appium v1.10.0
Appium-Python-Client  0.36
selenium              3.141.0
caps:
```
'customFindModules': {'ai': 'test-ai-classifier'},
'shouldUseCompactResponses': 'false'

```

```
d.find_element_by_custom("close")
 File "/Users/chen/.pyenv/versions/httprunner/lib/python3.6/site-packages/appium/webdriver/webdriver.py", line 423, in find_element_by_custom
    return self.find_element(by=MobileBy.CUSTOM, value=selector)
  File "/Users/chen/.pyenv/versions/httprunner/lib/python3.6/site-packages/appium/webdriver/webdriver.py", line 213, in find_element
    'value': value})['value']
  File "/Users/chen/.pyenv/versions/httprunner/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/chen/.pyenv/versions/httprunner/lib/python3.6/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
  File "/Users/chen/.pyenv/versions/httprunner/lib/python3.6/site-packages/appium/webdriver/errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "/Users/chen/.pyenv/versions/httprunner/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot destructure property `x` of 'undefined' or 'null'.
```

```
2019-01-21 17:39:39:907 - [HTTP] --> POST /wd/hub/session/da416914-dfea-4eef-9acf-6a2dceb6f154/element
2019-01-21 17:39:39:908 - [HTTP] {"using":"-custom","value":"close","sessionId":"da416914-dfea-4eef-9acf-6a2dceb6f154"}
2019-01-21 17:39:39:909 - [debug] [W3C (da416914)] Calling AppiumDriver.findElement() with args: ["-custom","close","da416914-dfea-4eef-9acf-6a2dceb6f154"]
2019-01-21 17:39:39:911 - [debug] [BaseDriver] Find plugin 'ai' requested; will attempt to use it from 'test-ai-classifier'
2019-01-21 17:39:39:912 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2019-01-21 17:39:39:913 - [ai] Retrieving current settings to check element response attributes
2019-01-21 17:39:39:913 - [ai] We will need to update settings to include element response attributes
2019-01-21 17:39:39:914 - [BaseDriver] Didn't know about setting 'elementResponseAttributes'. Are you sure you spelled it correctly? Proceeding anyway. Valid settings: imageMatchThreshold,fixImageFindScreenshotDims,fixImageTemplateSize,checkForImageElementStaleness,autoUpdateImageElementPosition,imageElementTapStrategy,ignoreUnimportantViews
2019-01-21 17:39:39:914 - [ai] Setting confidence threshold to default value of 0.2
2019-01-21 17:39:39:914 - [ai] Retrieving data for all leaf-node elements on screen
2019-01-21 17:39:39:915 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2019-01-21 17:39:39:915 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2019-01-21 17:39:39:916 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[not(child::*)]","context":"","multiple":true}}
2019-01-21 17:39:39:926 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[not(child::*)]","context":"","multiple":true}}
2019-01-21 17:39:39:930 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2019-01-21 17:39:39:939 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
2019-01-21 17:39:39:940 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//*[not(child::*)]' using 'XPATH' with the contextId: '' multiple: true
2019-01-21 17:39:40:183 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.ImageView, INSTANCE=0]
2019-01-21 17:39:40:183 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.ImageView, INSTANCE=0]
2019-01-21 17:39:40:184 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:447 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=0]
2019-01-21 17:39:40:447 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.TextView, INSTANCE=0]
2019-01-21 17:39:40:448 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:502 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.ImageView, INSTANCE=1]
2019-01-21 17:39:40:503 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.ImageView, INSTANCE=1]
2019-01-21 17:39:40:503 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:509 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=1]
2019-01-21 17:39:40:509 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.TextView, INSTANCE=1]
2019-01-21 17:39:40:510 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:525 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=2]
2019-01-21 17:39:40:525 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.TextView, INSTANCE=2]
2019-01-21 17:39:40:526 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:537 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.ImageView, INSTANCE=2]
2019-01-21 17:39:40:538 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.ImageView, INSTANCE=2]
2019-01-21 17:39:40:538 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:538 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=3]
2019-01-21 17:39:40:545 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.TextView, INSTANCE=3]
2019-01-21 17:39:40:545 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:554 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=4]
2019-01-21 17:39:40:555 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.TextView, INSTANCE=4]
2019-01-21 17:39:40:556 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:563 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=5]
2019-01-21 17:39:40:564 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.TextView, INSTANCE=5]
2019-01-21 17:39:40:564 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
2019-01-21 17:39:40:572 - [debug] [AndroidBootstrap] Received command result from bootstrap
2019-01-21 17:39:40:572 - [ai] Getting window size in case we need to scale screenshot
2019-01-21 17:39:40:573 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"getDeviceSize","params":{}}
2019-01-21 17:39:40:575 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"1"},{"ELEMENT":"2"},{"ELEMENT":"3"},{"ELEMENT":"4"},{"ELEMENT":"5"},{"ELEMENT":"6"},{"ELEMENT":"7"},{"ELEMENT":"8"},{"ELEMENT":"9"}]}
2019-01-21 17:39:40:578 - [debug] [AndroidBootstrap] Received command result from bootstrap
2019-01-21 17:39:40:579 - [ai] Getting screenshot to use for classifier
2019-01-21 17:39:40:579 - [debug] [ADB] Device API level: 28
2019-01-21 17:39:40:584 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"getDeviceSize","params":{}}
2019-01-21 17:39:40:585 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2019-01-21 17:39:40:585 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getDeviceSize
2019-01-21 17:39:40:586 - [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"height":1794,"width":1080}}
2019-01-21 17:39:41:596 - [ai] Turning screenshot into HTML image for use with canvas
2019-01-21 17:39:41:635 - [ai] Getting screenshot slices for each element
2019-01-21 17:39:41:639 - [ai] Resetting element response attribute setting to original value: undefined
2019-01-21 17:39:41:639 - [debug] [W3C (da416914)] Encountered internal error running command: TypeError: Cannot destructure property `x` of 'undefined' or 'null'.
2019-01-21 17:39:41:640 - [debug] [W3C (da416914)]     at rect (/Users/chen/node_modules/test-ai-classifier/lib/image.js:58:33)
2019-01-21 17:39:41:640 - [debug] [W3C (da416914)]     at elsAndImages (/Users/chen/node_modules/test-ai-classifier/lib/classifier.js:176:28)
2019-01-21 17:39:41:640 - [debug] [W3C (da416914)]     at Array.map (<anonymous>)
2019-01-21 17:39:41:640 - [debug] [W3C (da416914)]     at map (/Users/chen/node_modules/asyncbox/lib/asyncbox.js:75:26)
2019-01-21 17:39:41:640 - [debug] [W3C (da416914)]     at Generator.next (<anonymous>)
2019-01-21 17:39:41:640 - [debug] [W3C (da416914)]     at asyncGeneratorStep (/Users/chen/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
2019-01-21 17:39:41:641 - [debug] [W3C (da416914)]     at _next (/Users/chen/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
2019-01-21 17:39:41:641 - [debug] [W3C (da416914)]     at /Users/chen/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
2019-01-21 17:39:41:641 - [debug] [W3C (da416914)]     at new Promise (<anonymous>)
2019-01-21 17:39:41:641 - [debug] [W3C (da416914)]     at /Users/chen/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
2019-01-21 17:39:41:641 - [debug] [W3C (da416914)]     at asyncmap (/Users/chen/node_modules/asyncbox/build/lib/asyncbox.js:160:20)
2019-01-21 17:39:41:641 - [debug] [W3C (da416914)]     at getElementImages (/Users/chen/node_modules/test-ai-classifier/lib/classifier.js:174:30)
2019-01-21 17:39:41:642 - [debug] [W3C (da416914)]     at Object.getElementImages (/Users/chen/node_modules/test-ai-classifier/lib/classifier.js:270:32)
2019-01-21 17:39:41:642 - [debug] [W3C (da416914)]     at <anonymous>
2019-01-21 17:39:41:643 - [HTTP] <-- POST /wd/hub/session/da416914-dfea-4eef-9acf-6a2dceb6f154/element 500 1735 ms - 687
2019-01-21 17:39:41:643 - [HTTP]
^C2019-01-21 17:54:35:105 - [Appium] Received SIGINT - shutting down
2019-01-21 17:54:35:109 - [Logcat] Logcat terminated with code null, signal SIGINT
2019-01-21 17:54:35:110 - [UiAutomator] UiAutomator exited unexpectedly with code null, signal SIGINT
2019-01-21 17:54:35:110 - [debug] [UiAutomator] Moving to state 'stopped'
2019-01-21 17:54:35:112 - [debug] [AndroidDriver] Shutting down Android driver
```

**Comment by chenchengyuan** [comment]
when I using UIA2 as automationName, another error:
```
2019-01-21 23:23:26:346 - [ai] Getting window size in case we need to scale screenshot
2019-01-21 23:23:26:346 - [debug] [JSONWP Proxy] Matched '/window/current/size' to command name 'getWindowSize'
2019-01-21 23:23:26:346 - [debug] [JSONWP Proxy] Proxying [GET /window/current/size] to [GET http://localhost:8200/wd/hub/session/2680d204-682a-4b14-a8ff-73bb4039fab5/window/current/size] with body: {}
2019-01-21 23:23:26:359 - [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"2680d204-682a-4b14-a8ff-73bb4039fab5\",\"status\":0,\"value\":{\"height\":1794,\"width\":1080}}"
2019-01-21 23:23:26:360 - [ai] Getting screenshot to use for classifier
2019-01-21 23:23:26:364 - [debug] [JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
2019-01-21 23:23:26:365 - [debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/2680d204-682a-4b14-a8ff-73bb4039fab5/screenshot] with no body
2019-01-21 23:23:26:745 - [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"2680d204-682a-4b14-a8ff-73bb4039fab5\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAIAAACkA3BdAAAAAXNSR0IArs4c6QAAAANzQklUCAgI\\n2+FP4AAAIABJREFUeJzs3Xl8VPWh9\\/HfmTWzZLKRhEkgCWsgISEQuEC1SKGIa6vVtopa7fXi1evT\\nW7vd9tHrtdc+VntvfZ7aer11q9pir6VaF0oVUVFcQMCELCQkJGFJIPs2mX3OzDx\\/nDIN2ZjsJ8nn\\n\\/YcvmTlz5pf5nXNmvue3STt37hSYFnbu3Pk9anO6ePTqq6+++urJLgXGxs6dO6nNaYPanE527tz5\\n008+mexSTIT9Dz882UUYd4vvuKP6qacmuxQYY5rJLgAAAAAA9EVQAQAAAKA6BBUAAAAAqkNQAQAA\\nAKA6uskuACZUWSBQGQgkajRfjImZ7LJgtKqrq0+cOBEXF7d27drJLgsAAMAY+1tQ+eSTT9xud+\\/n\\nJEnS6\\/WxsbGZmZmJiYkjfg+Hw3H48OGTJ0\\/6fL6EhIScnJxly5ZpNMNuzPF4PB9\\/\\/LHJZLroooui\\nfInL5frss89ycnJmzZo13Leblor8\\/p86HF+IiVGCSliInR6PLIRFkrYMEl0qAoFjsiyE+JzBMFur\\nHdbbVcnyQZ+vIRj0hcNJGk2+wbDOYDBI0ug3HlBnKPSBz1cty+5QKEWrLTQY\\/s5gGMbrp5pjx449\\n\\/fTTq1evVoJKWVlZc3OzEOLiiy+OGaQ26+rq6urqhBCFhYUJCQnDervTp08XFxc3NzeHQiG73b5q\\n1ar09PRh7WGsLgVTVCgU2rdvnyzLQ1zEamtrT5w4IYQoKCgYp6vW6GthhtejYrxPtyhRm2Pozw5H\\nTyjU+xFJCKMkJWi1S2NiUnWTeWO3Ixjc09NT6fO5gsFUnW6t...
2019-01-21 23:23:26:747 - [ai] Turning screenshot into HTML image for use with canvas
2019-01-21 23:23:26:784 - [ai] Getting screenshot slices for each element
2019-01-21 23:23:27:344 - [ai] Making label predictions based on element images
2019-01-21 23:23:27:347 - [ai] Resetting element response attribute setting to original value: ""
2019-01-21 23:23:27:348 - [UiAutomator2] Forwarding the following settings to the UiAutomator2 server: ["elementResponseAttributes"]
2019-01-21 23:23:27:349 - [debug] [JSONWP Proxy] Matched '/appium/settings' to command name 'updateSettings'
2019-01-21 23:23:27:350 - [debug] [JSONWP Proxy] Proxying [POST /appium/settings] to [POST http://localhost:8200/wd/hub/session/2680d204-682a-4b14-a8ff-73bb4039fab5/appium/settings] with body: {"settings":{"elementResponseAttributes":""}}
2019-01-21 23:23:27:361 - [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"2680d204-682a-4b14-a8ff-73bb4039fab5","status":0,"value":true}
2019-01-21 23:23:27:399 - [debug] [W3C (dc5705c1)] Encountered internal error running command: Error: browserHTTPRequest is not supported outside the web browser without a fetch polyfill.
2019-01-21 23:23:27:400 - [debug] [W3C (dc5705c1)]     at new BrowserHTTPRequest (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-core/src/io/browser_http.ts:45:15)
2019-01-21 23:23:27:400 - [debug] [W3C (dc5705c1)]     at Object.browserHTTPRequest (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-core/src/io/browser_http.ts:443:10)
2019-01-21 23:23:27:400 - [debug] [W3C (dc5705c1)]     at FrozenModel.findIOHandler (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/src/executor/frozen_model.ts:86:30)
2019-01-21 23:23:27:401 - [debug] [W3C (dc5705c1)]     at FrozenModel.<anonymous> (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/src/executor/frozen_model.ts:101:10)
2019-01-21 23:23:27:401 - [debug] [W3C (dc5705c1)]     at step (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:32:23)
2019-01-21 23:23:27:401 - [debug] [W3C (dc5705c1)]     at Object.next (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:13:53)
2019-01-21 23:23:27:401 - [debug] [W3C (dc5705c1)]     at /Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:7:71
2019-01-21 23:23:27:402 - [debug] [W3C (dc5705c1)]     at new Promise (<anonymous>)
2019-01-21 23:23:27:402 - [debug] [W3C (dc5705c1)]     at __awaiter (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:3:12)
2019-01-21 23:23:27:402 - [debug] [W3C (dc5705c1)]     at FrozenModel.load (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:113:16)
2019-01-21 23:23:27:402 - [debug] [W3C (dc5705c1)]     at Object.<anonymous> (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/src/executor/frozen_model.ts:297:15)
2019-01-21 23:23:27:403 - [debug] [W3C (dc5705c1)]     at step (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:32:23)
2019-01-21 23:23:27:403 - [debug] [W3C (dc5705c1)]     at Object.next (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:13:53)
2019-01-21 23:23:27:403 - [debug] [W3C (dc5705c1)]     at /Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:7:71
2019-01-21 23:23:27:403 - [debug] [W3C (dc5705c1)]     at new Promise (<anonymous>)
2019-01-21 23:23:27:403 - [debug] [W3C (dc5705c1)]     at __awaiter (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:3:12)
2019-01-21 23:23:27:404 - [debug] [W3C (dc5705c1)]     at Object.loadFrozenModel (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model.js:210:12)
2019-01-21 23:23:27:404 - [debug] [W3C (dc5705c1)]     at loadFrozenModel (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/_test-ai-classifier@2.1.0@test-ai-classifier/lib/classifier.js:27:30)
2019-01-21 23:23:27:404 - [debug] [W3C (dc5705c1)]     at getModel (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/_test-ai-classifier@2.1.0@test-ai-classifier/lib/classifier.js:90:23)
2019-01-21 23:23:27:404 - [debug] [W3C (dc5705c1)]     at predictionsFromImages (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/_test-ai-classifier@2.1.0@test-ai-classifier/lib/classifier.js:210:23)
2019-01-21 23:23:27:404 - [debug] [W3C (dc5705c1)]     at Object.getMatchingElements (/Users/chen/.nvm/versions/node/v8.14.0/lib/node_modules/appium/node_modules/_test-ai-classifier@2.1.0@test-ai-classifier/lib/classifier.js:271:18)
2019-01-21 23:23:27:405 - [debug] [W3C (dc5705c1)]     at <anonymous>
2019-01-21 23:23:27:443 - [HTTP] <-- POST /wd/hub/session/dc5705c1-603e-4e7a-b6fe-52ac84d214f6/element 500 2533 ms - 743
```

**Comment by jlipps** [comment]
Yes, this won't work with the old android driver.

As for the uiautomator2 error, that is coming from tensorflowjs. Did you try to google it to see what it could be?

**Comment by chenchengyuan** [comment]
Yes, I did it, somebody says like this：
https://github.com/tensorflow/tfjs/issues/759
I think it was not for me, I think there is a problem with my environment.
Then I reinstalled the Appium and test-ai-classifier, now it can be used.
Thank you！
