### ISSUE TITLE
scroll not working

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [cloudgrey-io/appiumpro#38]
I am trying to scroll using the methods provided here but I endup with an error any Idea?

https://github.com/cloudgrey-io/appiumpro/blob/22c7344f00cfc1c228552b13832d2b2ffd2027f7/java/src/test/java/Edition107_Base.java#L23

I am calling the following in my test I am using appium java client 7.0.0

scroll(ScrollDirection.DOWN);

But I am getting following error...
```java
org.openqa.selenium.UnsupportedCommandException: actions
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:618)
	at com.test.qa.pages.DriverPageUtil.swipe(DriverPageUtil.java:368)

**Comment by Prasannajnaeyulu** [comment]
@jlipps @Jonahss If you have any leads or workarounds for this problem can you please help me with.

**Comment by Prasannajnaeyulu** [comment]
@jlipps and @Jonahss any help on this please?

**Comment by jlipps** [comment]
I'm not sure. You'd have to paste your appium logs to see what the issue might be.

**Comment by Prasannajnaeyulu** [comment]
@jlipps thanks for the response looks like the error is thrown from appium java client side itself. I can't see anything in appium server log. May I know is this scroll function works for sepcific selenium and appium java client versions? I am using appium java client 7.0.0 and selenium java 3.141.59

**Comment by Prasannajnaeyulu** [comment]
I could see in your repo. you are using 
```java
testImplementation group: 'io.appium', name: 'java-client', version: '7.3.0'
testImplementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.13.0'

**Comment by jlipps** [comment]
Then I guess it's a client version issue. Try using my versions instead and see? I don't really keep up with the Java client, you can report an issue at the Appium java client repo if you want.

**Comment by Prasannajnaeyulu** [comment]
Sure I will give a try with those versions thanks
